### ISSUE TITLE
Error generating xmr-stak-nvidiaCuda_generated_cuda_extra.cu.o

### ISSUE THREAD

**Issue by peterwillcn** [arsenicks/local-mining-xmr-ansible#1]
[  4%] Building NVCC (Device) object CMakeFiles/xmr-stak-nvidiaCuda.dir/nvcc_code/xmr-stak-nvidiaCuda_generated_cuda_extra.cu.o
CMake Error at xmr-stak-nvidiaCuda_generated_cuda_extra.cu.o.cmake:207 (message):
  Error generating
  /home/arsenick/xmr-stak-nvidia-1.1.1-1.4.0/CMakeFiles/xmr-stak-nvidiaCuda.dir/nvcc_code/./xmr-stak-nvidiaCuda_generated_cuda_extra.cu.o

CMakeFiles/xmr-stak-nvidiaCuda.dir/build.make:70: recipe for target 'CMakeFiles/xmr-stak-nvidiaCuda.dir/nvcc_code/xmr-stak-nvidiaCuda_generated_cuda_extra.cu.o' failed
make[2]: *** [CMakeFiles/xmr-stak-nvidiaCuda.dir/nvcc_code/xmr-stak-nvidiaCuda_generated_cuda_extra.cu.o] Error 1
CMakeFiles/Makefile2:67: recipe for target 'CMakeFiles/xmr-stak-nvidiaCuda.dir/all' failed
make[1]: *** [CMakeFiles/xmr-stak-nvidiaCuda.dir/all] Error 2
Makefile:127: recipe for target 'all' failed
make: *** [all] Error 2

**Comment by arsenicks** [comment]
Hi, As stated in the readme the xmr-stak-nvidia part of this playbook is not working right now. I will remove this project soon and replace it with the new one I've done using docker.

**Comment by arsenicks** [comment]
I'll archive this repo as I stopped working on this code to use containers.
